我的任务全焊完了
VM-Chinese-translate-group/MC-Eternal pull request #18
Opened 2023-01-02 06:04 UTC by 3093FengMing

```
scripts:
----Events（修改）
----Harvestcraft
----MysticalAgri
----NoSpacePortals
----AdvRocketry
----Akt
----Tooltip（修改）
----EBWizardry
----Mekanism
----MiscCrafting
Mod:
----ancientspellcraft
----architecturecraft
----artifacts
----biomestaff
----cqrepoured
----dimdoors
----fossil
----mcwroofs
----morphspellpack
----simplycats
----stupidthings
----treasure2
----dungeontactics（i18n）
----moartinkers
FTBQ:
----b5f36009（极光幽境）
----147ca0a1（阿图姆）
Others:
----mainmenu.json
----tips.cfg
----bountiful/rewards.json
```

2023-01-03 00:15 UTC, nageih commented on config/ftbquests/normal/chapters/147ca0a1/4deccbba.snbt
> +		"在石棺周围的四个錾制石灰岩砖上，沿着图案放置皇家火把，确保火把都点亮了。"
```suggestion
		"在石棺周围的四个雕纹石灰岩砖上，沿着图案放置皇家火把，确保火把都点亮了。"
```

2023-01-03 00:29 UTC, nageih commented on config/ftbquests/normal/chapters/147ca0a1/87c00157.snbt
> +	description: "&o从阿图姆收集所有文物",
```suggestion
	description: "&o从阿图姆收集所有神器",
```

2023-01-03 00:29 UTC, nageih commented on config/ftbquests/normal/chapters/147ca0a1/87c00157.snbt
> +	description: "&o从阿图姆收集所有文物",
模组对artifact的翻译是神器

2023-01-03 00:29 UTC, nageih commented on config/ftbquests/normal/chapters/147ca0a1/93182620.snbt
> +	description: "&o探索时要格外小心，你应该最不想做激怒一些古老的亡灵或其他什么东西",
```suggestion
	description: "&o探索时要格外小心，你应该不想激怒一些古老的亡灵或其他的东西",
```

2023-01-03 00:29 UTC, nageih commented on config/tips.cfg
> +	传说阿图姆埋藏着许多珍宝，有些人可能愿意购买……
```suggestion
	传说阿图姆中埋藏着许多珍宝，有些人可能更愿意购买……
```

2023-01-03 00:29 UTC, nageih commented on scripts/Harvestcraft.zs
> +	itemUtils.getItem("harvestcraft:"~gardens~"garden").addTooltip(format.red("禁用，请从农场贸易的贸易站中购买潘马斯农场中的种子"));
```suggestion
	itemUtils.getItem("harvestcraft:"~gardens~"garden").addTooltip(format.red("禁用，请从农场贸易的农贸市场中购买潘马斯农场中的种子"));
```

2023-01-03 00:29 UTC, nageih commented on scripts/Tooltip.zs
> +	itemUtils.getItem("quark:candle", meta).addShiftTooltip(format.gold("提高矩阵内附魔的速率："), format.gold("按住 SHIFT 查看受影响的魔法"));
```suggestion
	itemUtils.getItem("quark:candle", meta).addShiftTooltip(format.gold("提高矩阵附魔的速率："), format.gold("按住 SHIFT 查看受影响的附魔"));
```

2023-01-03 15:03 UTC, yiqv requested changes
审核到tooltips
请更改
以及贴图不通过

2023-01-03 15:03 UTC, yiqv commented on config/ftbquests/normal/chapters/147ca0a1/93182620.snbt
> +		title: "揭开一座古老的金字塔的面纱",
```suggestion
		title: "揭开一座古老金字塔的面纱",
```
的的的的的的的的的的

2023-01-03 15:03 UTC, yiqv commented on config/ftbquests/normal/chapters/147ca0a1/99a4bfed.snbt
> +	description: "&o一个沙漠星球，但并非没有生命，奇怪的是恰恰相反……一股古老的力量觉醒了，你有一股调查的冲动。又有哪些宝藏未被发现？只有一种方法可以找到！",
原pr已更正，请再次更改

2023-01-03 15:03 UTC, yiqv commented on config/tips.cfg
> +	你不能从驯服箭上之鼠
语句不通顺，请检查

2023-01-03 15:03 UTC, yiqv commented on config/tips.cfg
> +	在永恒的MC中，陨石只能从深渊世界中发现
```suggestion
	在永恒的MC中，陨石只能在深渊世界中发现
```

2023-01-03 15:03 UTC, yiqv commented on config/tips.cfg
> +	以前从未接触过某个模组？加入 Discord 获得帮助！
```suggestion
	以前从未接触过的模组？加入 Discord 获得帮助！
```

2023-01-03 15:03 UTC, yiqv commented on config/tips.cfg
> +	大多数Boss生物都被大大加强了，做好准备吧。
```suggestion
	大多数Boss生物都被加强了，做好准备吧。
```

2023-01-03 15:03 UTC, yiqv commented on config/tips.cfg
> +	不不不！不要把满满的背包放在你的ME系统里！
没有问题，单纯想起之前做过，一背包东西拿不出来了

2023-01-03 15:03 UTC, yiqv commented on config/tips.cfg
> +	瓶子里的时间来自真实时间，你可以用它来加速世界上的方块！
语句极其不通顺，请检查

2023-01-03 15:03 UTC, yiqv commented on config/tips.cfg
> +	你可以在网络工具中存储AE升级卡
有问题，请检查

2023-01-03 15:03 UTC, yiqv commented on scripts/Tooltip.zs
> +<immersiveengineering:railgun>.addTooltip(format.lightPurple("伤害放大至 40 倍"));
```suggestion
<immersiveengineering:railgun>.addTooltip(format.lightPurple("伤害被增强 40 倍"));
```

2023-01-03 15:03 UTC, yiqv commented on scripts/Tooltip.zs
> +<immersiveengineering:revolver>.addTooltip(format.lightPurple("子弹伤害放大至约 15 倍"));
```suggestion
<immersiveengineering:revolver>.addTooltip(format.lightPurple("子弹伤害被增强约 15 倍"));
```

2023-01-03 15:03 UTC, yiqv commented on scripts/Tooltip.zs
> +<thaumicaugmentation:impulse_cannon>.addTooltip(format.lightPurple("伤害放大至 20 倍"));
```suggestion
<thaumicaugmentation:impulse_cannon>.addTooltip(format.lightPurple("伤害被增强 20 倍"));
```

2023-01-03 15:14 UTC, 3093FengMing commented on scripts/Tooltip.zs
> +<immersiveengineering:railgun>.addTooltip(format.lightPurple("伤害放大至 40 倍"));
你这都跟原意不符了

2023-01-03 15:29 UTC, 3093FengMing commented on config/tips.cfg
> +	你不能从驯服箭上之鼠
真没看出来

2023-01-05 13:03 UTC, 3093FengMing commented on config/tips.cfg
> +	瓶子里的时间来自真实时间，你可以用它来加速世界上的方块！
已修改

2023-01-05 13:03 UTC, 3093FengMing commented on config/tips.cfg
> +	在永恒的MC中，陨石只能从深渊世界中发现
已修改

2023-01-05 13:04 UTC, 3093FengMing commented on config/ftbquests/normal/chapters/147ca0a1/93182620.snbt
> +		title: "揭开一座古老的金字塔的面纱",
改了

2023-01-05 13:04 UTC, 3093FengMing commented on scripts/Tooltip.zs
> +	itemUtils.getItem("quark:candle", meta).addShiftTooltip(format.gold("提高矩阵内附魔的速率："), format.gold("按住 SHIFT 查看受影响的魔法"));
已修改

2023-01-05 13:04 UTC, 3093FengMing commented on config/tips.cfg
> +	传说阿图姆埋藏着许多珍宝，有些人可能愿意购买……
已修改

2023-01-05 13:06 UTC, 3093FengMing commented on config/ftbquests/normal/chapters/147ca0a1/93182620.snbt
> +	description: "&o探索时要格外小心，你应该最不想做激怒一些古老的亡灵或其他什么东西",
已修改

2023-01-11 14:05 UTC, yiqv commented on config/bountiful/rewards.json
> +    "nbt_data": "{display:{Lore:[\"被沙漠中的一个村民发现，这把刀片喜欢对使用者耳语\"]},ench:[{id:16,lvl:4}]}",
```suggestion
    "nbt_data": "{display:{Lore:[\"一个生活在沙漠中的村民发现，这把刀片喜欢对它的使用者耳语\"]},ench:[{id:16,lvl:4}]}",
```

2023-01-11 14:05 UTC, yiqv commented on config/ftbquests/normal/chapters/147ca0a1/99a4bfed.snbt
> +	description: "&o一个沙漠星球，但并非没有生命，奇怪的是恰恰相反……一股古老的力量觉醒了，你有一股调查的冲动。又有哪些宝藏未被发现？只有一种方法可以找到！",
```suggestion
	description: "&o一个沙漠星球，但并非没有生命，奇怪的是恰恰相反。。。一股古老的力量正在觉醒了，使你求知探索的内心愈发冲动。有哪些未被发现的宝藏？只有一种方式能找到答案！",
```

2023-01-11 14:05 UTC, yiqv commented on config/ftbquests/normal/chapters/b5f36009/21d77837.snbt
> +	description: "&o这颗美丽的星球由一片幽暗、寒凉、宁谧的森林组成，森林里生长着神奇瑰丽的植物，也有隐藏在其中的古老废墟在月光下熠熠生辉。一切景象都那么美好。",
```suggestion
	description: "&o这颗美丽的星球被一片幽暗、寒凉、宁谧的森林覆盖，森林里生长着神奇瑰丽的植物，也隐藏着古老的废墟在月光下熠熠生辉。一切景象都那么美好。",
```

2023-01-11 14:05 UTC, yiqv commented on config/tips.cfg
> +	你可以在网络工具中存储AE升级卡
确定无问题

2023-01-11 14:05 UTC, yiqv commented on scripts/AdvRocketry.zs
> +	usualobjects.addTooltip(format.red(ohnoeffort[usualobjects]~" 无法正常前往。\n你需要使用高级火箭前往。"));
```suggestion
	usualobjects.addTooltip(format.red(ohnoeffort[usualobjects]~" 无法正常前往。\n你需要使用高级火箭才能到达。"));
```

2023-01-11 14:05 UTC, yiqv commented on scripts/MiscCrafting.zs
> +mods.thaumcraft.Infusion.registerRecipe("mce_ratification_stone", "", <morphspellpack:charm_druid_stone>.withTag({Entity: "rats:rat", display:{Name:"认可之石",Lore:["我成了老鼠，奶酪的消费者。","变形为老鼠15秒。","使用时不消耗"]}
```suggestion
mods.thaumcraft.Infusion.registerRecipe("mce_ratification_stone", "", <morphspellpack:charm_druid_stone>.withTag({Entity: "rats:rat", display:{Name:"认可之石",Lore:["我成了老鼠，奶酪的消费者。","变形为老鼠15秒。","使用时不会消耗"]}}), 12, 
```

2023-01-11 14:05 UTC, yiqv commented on scripts/MysticalAgri.zs
> +		itemUtils.getItem("mysticalagriculture:"~theseeds~"_essence").addTooltip(format.red("你处于普通模式，因此此物品被禁用且无用。"));
暂时不知道那个游戏模式切换的按钮汉化了没，没焊就将普通改回normal

2023-01-11 14:05 UTC, yiqv commented on 资源包/assets/cqrepoured/lang/zh_cn.lang
> +description.staff.name=一根长而结实的棍子。也许有人知道如何运用魔法。
一根长而结实的棍子。也许有人知道如何运用魔法。
前后文不搭嘎？？

2023-01-12 04:11 UTC, yiqv commented on 资源包/assets/cqrepoured/lang/zh_cn.lang
> +description.staff.name=一根长而结实的棍子。也许有人知道如何运用魔法。
快修改，宝

2023-01-12 04:38 UTC, 3093FengMing commented on 资源包/assets/cqrepoured/lang/zh_cn.lang
> +description.staff.name=一根长而结实的棍子。也许有人知道如何运用魔法。
JSJ已修改

2023-01-12 05:10 UTC, merged