高级火箭汉化
VM-Chinese-translate-group/MC-Eternal pull request #30
Opened 2023-01-11 04:49 UTC by zizunsi

高级火箭汉化

2023-01-11 06:06 UTC, Wulian233 requested changes
请更改标点符号，其他的没问题，谢谢。

2023-01-11 06:06 UTC, Wulian233 commented on config/ftbquests/classic/chapters/92b211dd/091e6c54.snbt
> +	title: "升空!",
```suggestion
	title: "升空！",
```

2023-01-11 06:06 UTC, Wulian233 commented on config/ftbquests/classic/chapters/92b211dd/14caadfa.snbt
> +		"5. 进入火箭，点击'C'进入火箭设置菜单 (自行查看按键绑定)",
```suggestion
		"5. 进入火箭，点击'C'进入火箭设置菜单（自行查看按键绑定）",
```

2023-01-11 06:06 UTC, Wulian233 commented on config/ftbquests/classic/chapters/92b211dd/14caadfa.snbt
> +		"7. 点击'空格键'升空！!"
```suggestion
		"7. 点击“空格键”升空！"
```

2023-01-11 06:06 UTC, Wulian233 commented on config/ftbquests/classic/chapters/92b211dd/28e9bc60.snbt
> +	description: "氧气排放口可用于使封闭的房间空间充满氧气，而不需要从密封盔甲中获得氧气。每个二氧化碳净化器可使其不消耗50%的氧气，最高可以达到100%!",
```suggestion
	description: "氧气排放口可用于使封闭的房间空间充满氧气，而不需要从密封盔甲中获得氧气。每个二氧化碳净化器可使其不消耗50%的氧气，最高可以达到100％！",
```

2023-01-11 06:06 UTC, Wulian233 commented on config/ftbquests/classic/chapters/92b211dd/74150491.snbt
> +	title: "都充好气了!",
```suggestion
	title: "都充好气了！",
```

2023-01-11 06:06 UTC, Wulian233 commented on config/ftbquests/normal/chapters/92b211dd/14caadfa.snbt
> +		"7. 点击'空格键'升空！!"
```suggestion
		"7. 点击“空格键”升空！"
```

2023-01-11 06:06 UTC, Wulian233 commented on config/ftbquests/normal/chapters/92b211dd/28e9bc60.snbt
> +	description: "氧气排放口可用于使封闭的房间空间充满氧气，而不需要从密封盔甲中获得氧气。每个二氧化碳净化器可使其不消耗50%的氧气，最高可以达到100%!",
```suggestion
	description: "氧气排放口可用于使封闭的房间空间充满氧气，而不需要从密封盔甲中获得氧气。每个二氧化碳净化器可使其不消耗50％的氧气，最高可以达到100％！",
```

2023-01-11 06:06 UTC, Wulian233 commented on config/ftbquests/normal/chapters/92b211dd/74150491.snbt
> +	title: "都充好气了!",
```suggestion
	title: "都充好气了！",
```

2023-01-11 06:30 UTC, Wulian233 requested changes

2023-01-11 06:30 UTC, Wulian233 commented on config/ftbquests/classic/chapters/92b211dd/bb9f8d30.snbt
> +		"&l在身上带着装有火箭燃料的液体容器时，点击液体任务图标，即可提交!"
```suggestion
		"&l在身上带着装有火箭燃料的液体容器时，点击液体任务图标即可提交！"
```

2023-01-11 06:30 UTC, Wulian233 commented on config/ftbquests/normal/chapters/92b211dd/091e6c54.snbt
> +	title: "升空!",
```suggestion
	title: "升空！",
```

2023-01-11 06:30 UTC, Wulian233 commented on config/ftbquests/normal/chapters/92b211dd/14caadfa.snbt
> +		"&6&l登上月球的傻瓜式服务&r &o(如果你忽略了前面所有的任务文本 >:C)",
```suggestion
		"&6&l登上月球的傻瓜式服务&r &o（如果你忽略了前面所有的任务文本 >:C）",
```

2023-01-11 06:30 UTC, Wulian233 commented on config/ftbquests/normal/chapters/92b211dd/14caadfa.snbt
> +		"5. 进入火箭，点击'C'进入火箭设置菜单 (自行查看按键绑定)",
```suggestion
		"5. 进入火箭，按“C”进入火箭设置菜单(自行查看按键绑定）",
```

2023-01-11 06:30 UTC, Wulian233 commented on config/ftbquests/normal/chapters/92b211dd/db9592f2.snbt
> +		title: "§7§l点击我获取链接!",
```suggestion
		title: "§7§l点我获取链接！",
```

2023-01-12 10:03 UTC, yiqv commented on config/ftbquests/classic/chapters/92b211dd/0479a7a1.snbt
> +	description: "§7§o用来飞往太空的一些机器比你可能知道的更加昂贵……",
```suggestion
	description: "§7§o用来飞往太空的一些机器可能比你知道的更加昂贵……",
```

2023-01-12 10:03 UTC, yiqv commented on config/ftbquests/classic/chapters/92b211dd/14caadfa.snbt
> +		"7. 点击“空格键”升空！"
```suggestion
		"7. 敲击“空格键”升空！"
```

2023-01-12 10:03 UTC, yiqv commented on config/ftbquests/classic/chapters/92b211dd/14caadfa.snbt
> +		"5. 进入火箭，点击'C'进入火箭设置菜单（自行查看按键绑定）",
```suggestion
		"5. 进入火箭，按'C'进入火箭设置菜单（自行查看按键绑定）",
```

2023-01-12 10:03 UTC, yiqv commented on config/ftbquests/classic/chapters/92b211dd/604d9e61.snbt
> +	description: "将水分解成氢气和氧气，这是生产火箭燃料和填充你的密封的盔甲所需要的。",
```suggestion
	description: "将水分解成氢气和氧气，这是生产火箭燃料和填充你的密封的盔甲所需要的。  2H2O =电解= 2H2↑ +O2↑",
```
整个活

2023-01-12 10:08 UTC, merged