1
VM-Chinese-translate-group/MC-Eternal pull request #39
Opened 2023-06-25 08:02 UTC by yiqv

2023-06-26 04:19 UTC, Wulian233 requested changes

2023-06-26 04:19 UTC, Wulian233 commented on config/ftbquests/classic/chapters/bec752d7/15daf035.snbt
> +		"&5元始杵&7&d镐铲合一&7,是一把相当强力的工具.它拥有着像&5挖掘核心&7一样的&63x3挖掘范围&7及&6炽心&7能力,同时添加了&6自我修复能力！"
```suggestion
		"&5元始杵&7&d镐铲合一&7,是一把相当强力的工具.它拥有着像&5挖掘核心&7一样的&63x3挖掘范围&7及&6炽心&7能力，同时添加了&6自我修复能力！"
```

2023-06-26 04:19 UTC, Wulian233 commented on config/ftbquests/classic/chapters/bec752d7/40a60429.snbt
>  		command: "/tellraw @p {\"text\":\"§dYou did read the description of §5\\\"§lRead the Book, or you'll be Cooked!\\\"§d, right §5Thaumaturge§d?\"}"
```suggestion
 		command: "/tellraw @p {\"text\":\"§dYou did read the description of §5\\\"§lRead the Book, or you'll be Cooked!\\\"§d, right §5Thaumaturge§d?\"}"
```
没有翻译，曲艺去重做

2023-06-26 04:19 UTC, Wulian233 commented on config/ftbquests/classic/chapters/bec752d7/8eb5f2cb.snbt
>  		command: "/tellraw @p {\"text\":\"§5§l我打赌你在点这个之前没有阅读描述! 赶紧去读它！\"}"
```suggestion
 		command: "/tellraw @p {\"text\":\"§5§l我打赌你在点这个之前没有阅读描述！赶紧去读它！\"}"
```

2023-06-30 13:16 UTC, yiqv commented on config/ftbquests/classic/chapters/bec752d7/40a60429.snbt
>  		command: "/tellraw @p {\"text\":\"§dYou did read the description of §5\\\"§lRead the Book, or you'll be Cooked!\\\"§d, right §5Thaumaturge§d?\"}"
没有翻译，树苗重做关我屁事（（

2023-06-30 13:30 UTC, merged